version: '3'
services:
  admin:
    environment:
      - ADMIN=DEV
    image: svinerus/sova-backend
    build: ../backend
    volumes:
      - ./run:/run
      - ../backend/static:/backend/static
      - ../backend/db:/backend/db
      - ../backend/:/backend
    ports:
      - 8000:8000

  bot:
    stdin_open: true
    tty: true
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - REDIS_HOST=redis
    depends_on:
      - redis
    image: svinerus/sova-backend
    build: ../backend
    volumes:
      - ./run:/run
      - ../backend/db:/backend/db
      - ../backend/:/backend

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data


volumes:
  redis-data:

#  frontend:
